version: '1.0'

services:
  express-service:
    image: express-mysql-image
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  mysql-service:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - 3300:3300
    volumes:
      - mysql_volumes:/var/lib/mysql

volumes:
  mysql_volumes:
