version: '1.0'

services:
  mysql-service:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - 3300:3300
    volumes:
      - mysql_volumes:/var/lib/mysql
    networks:
      - my-network

  express-service:
    image: express-mysql-image
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-service
    ports:
      - 3000:3000
    networks:
      - my-network

volumes:
  mysql_volumes:

networks:
  my-network:
